### ISSUE TITLE
Conseil de chose à améliorer

### ISSUE THREAD

**Issue by Zach3292** [Evolution2626/PROG-2024#13]
Ici: 
https://github.com/Evolution2626/PROG-2024/blob/09430458b92b9fb1d862e9676e147011fbf451b5/src/main/java/frc/robot/subsystems/ClimberInAnBox.java#L21
Remplacer climberOut par un enum de position qui a deux positions, genre une en haut et une en bas
et ici:
https://github.com/Evolution2626/PROG-2024/blob/09430458b92b9fb1d862e9676e147011fbf451b5/src/main/java/frc/robot/subsystems/ClimberInAnBox.java#L59-L64
Remplacer vos deux fonctions par setPosition() et getPosition() qui prennent l'enum en paramètres

Ici:
https://github.com/Evolution2626/PROG-2024/blob/09430458b92b9fb1d862e9676e147011fbf451b5/src/main/java/frc/robot/subsystems/ClimberInAnBox.java#L66-L72
Comment faites-vous pour désactiver le ratchet

Ici: 
https://github.com/Evolution2626/PROG-2024/blob/09430458b92b9fb1d862e9676e147011fbf451b5/src/main/java/frc/robot/subsystems/ClimberInAnBox.java#L20
Il pourrait possiblement aussi y avoir un enum pour le ratchet qui a deux positions, genre activé ou desactivé. La boolean est pas si pire dans ce cas là

**Comment by Thierry-Lachance** [comment]
complete sauf climber pour safety
