### ISSUE TITLE
Interrogations

### ISSUE THREAD

**Issue by technonerdz** [Evolution2626/PROG-2024#7]
Pourquoi pas instantCommand?
https://github.com/Evolution2626/PROG-2024/blob/95185b02d60944905d1f15cd44ddd9b1e7274947/src/main/java/frc/robot/commands/ResetEncoderCommand.java#L10

Pourquoi pas instantCommand? execute() vide anyway
https://github.com/Evolution2626/PROG-2024/blob/df2c25a03551ff3559c85c17e112f6fe9dcb27cb/src/main/java/frc/robot/commands/StopShooterCommand.java#L10

Est-ce que vous pensez que nous allons pouvoir toujours partir du même point dépendamment de nos partenaires d'alliances?
https://github.com/Evolution2626/PROG-2024/blob/df2c25a03551ff3559c85c17e112f6fe9dcb27cb/src/main/java/frc/robot/commands/AutoShootToSideCommand.java#L21

Pourquoi garder des fichiers Java de commandes que nous utilisons pas?

**Comment by Thierry-Lachance** [comment]
le mode autonome peut partir de plusieurs point tant que après avoir avancer 1.75 m il voit le april tag de la target(donc pas d'importance sur quelle coter ce situe le target)(déjà tester) pour les instant command c'est qu'on les a simplifier par après.(à modifier ce soir). pour les command pas utiliser c'est surtout des vieux test.(a effacer ce soir)

**Comment by Thierry-Lachance** [comment]
?
